### ISSUE TITLE
Handling text overflow

### ISSUE THREAD

**Issue by jverhoelen** [porsche-design-system/porsche-design-system-contribution#60]
Hey there,
with the headline (React) component we're facing the following issue: line breaks are word-wrapped with hyphens and we're not able to deactivate it:

<img width="667" alt="Screenshot 2022-03-23 at 13 23 01" src="https://user-images.githubusercontent.com/6791360/159698974-7cd76347-98b8-457e-8c98-00335647fde2.png">

This is due to the CSS rule `hyphens: auto`. In at least one specific headline we don't want this behaviour to happen. The real phrasing we're using there is not word-breaking nicely. In the future we also can't prevent the word-breaking to happen to due responsiveness and i18n.
If we change that to `hyphens: none` this is our intended behaviour:

<img width="540" alt="Screenshot 2022-03-23 at 13 23 07" src="https://user-images.githubusercontent.com/6791360/159699516-7b7b09a9-3bd4-4a05-a48b-47b8f4ca43bf.png">

Would it be an option to provide a component property that lets us overwrite the default behaviour nicely?

**Comment by stephanschroeter** [comment]
Hi [jverhoelen](https://github.com/jverhoelen), we could add a prop to the headline component which enables/disables the behavior. We'll discuss this with our PO as soon as he's back from vacation (~March 28). If need a quickfix/workaround in the meantime you could simply wrap your text node with a span and apply the style `hypens: none`.

```
<p-headline>
  <span style="hypens: none;">You Text</span>
</p-headline>
```

**Comment by stephanschroeter** [comment]
Hi [jverhoelen](https://github.com/jverhoelen), we could add a prop to the headline component which enables/disables the behavior. We'll discuss this with our PO as soon as he's back from vacation (~March 28). If a quickfix/workaround is needed in the meantime then you could simply wrap your text node with a span and apply the style `hypens: none`.

```
<p-headline>
  <span style="hypens: none;">You Text</span>
</p-headline>
```

**Comment by jverhoelen** [comment]
Thanks for your quick reply @stephanschroeter. I'll add @tbinias to the loop because I'll be leaving the project soon.

**Comment by marcelbertram** [comment]
Removed hypens for headlines in 2.12.0
